### ISSUE TITLE
complete side bar

### ISSUE THREAD

**Issue by uneemo-99** [hznutx/react-point-of-sale#6]
- [x] add image logo or text logo 
- [x] add action menu
- [x] add logout button

![Image](https://user-images.githubusercontent.com/77600407/250298737-0cb142c8-b6ec-43f6-a42e-4f1ce2e2056c.png)

**Comment by hznutx** [comment]
Hi! @uneemo-99 kindly find update tesk completed as attached.
![image](https://github.com/hznutx/react-point-of-sale/assets/126380434/c4d6a872-7f36-4d7e-bfac-170253099837)

**Comment by uneemo-99** [comment]
ว้าว ดู ดี หนิ
