### ISSUE TITLE
complete right bar

### ISSUE THREAD

**Issue by uneemo-99** [hznutx/react-point-of-sale#8]
- [x] user info
- [x] order detail
- [x] payment

* blue line for main component
* green line for sub component

![Image](https://user-images.githubusercontent.com/77600407/251477923-6f39fe9e-5661-42c2-925f-97ebea81cadf.png)

**Comment by hznutx** [comment]
Hi uneemo,
Goodday ! your assigned to create side bar all done!
Actually,I've more including datail other components than 90% to go fully speed
![image](https://github.com/hznutx/react-point-of-sale/assets/126380434/36a66c4e-a059-4a20-a9e3-cfe88d13edf6)
Please help check updates on this in attachment.
🚀  add filter category Bar with scrollable  button 💻 
![image](https://github.com/hznutx/react-point-of-sale/assets/126380434/903096d7-5ca8-468b-a534-9b6c31d85012)

🚀  modal popup for confirm & calculate order [waiting Backend guidelines ]
+ Calcular with price menu json by UseState 
![image](https://github.com/hznutx/react-point-of-sale/assets/126380434/4a78460c-14bc-4ec2-be09-095af65d494a)
+ map Json array data to show all result coffee menu 
+ add order button
+ scrollable main data & side bar 
![image](https://github.com/hznutx/react-point-of-sale/assets/126380434/8ab6e3f5-b10a-4758-be3d-b114c2825b5d)

Hope you'll be nice to guidance with these things,Thanks.
